name: workflow CI

on:
  push:
    branches:
      - workflow_branch
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@da26677639ccfb4615f1acc52d1fc3dc89152490

      - name: Cache code
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
            restore-keys: ${{runner.os}}-node


      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Check Node installation
        run: node --version
      
      - name: install dependencies
        run: npm install
        shell: bash

      - name: List project files
        run: ls

      - name: Run app.js
        run: timeout 10 npm run start
        shell: bash
